version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./db.sqlite3:/app/data/db.sqlite3
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=django-insecure-t+zr-7-l-tcctnkca!c!+6g0yuysp_*^wv782_z5_*45czl6uu
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/1
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis
      - rabbitmq

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./movie-booking-frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management interface
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  celery_worker:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    command: celery -A core worker -l info
    depends_on:
      - backend
      - redis
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery_beat:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    command: celery -A core beat -l info
    depends_on:
      - backend
      - redis
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  flower:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    command: celery -A core flower
    ports:
      - "5555:5555"
    depends_on:
      - backend
      - redis
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

volumes:
  sqlite_data:
  redis_data:
  rabbitmq_data: