# Generated by Django 5.1.2 on 2024-12-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_seats',
            field=models.JSONField(default=list),
        ),
    ]
